# Generated by Django 4.2.3 on 2023-07-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
