# Generated by Django 4.2.3 on 2023-07-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
    ]
